POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "ahmed",
  "lastName": "mohsen",
  "email": "mohsen@gmail.com",
  "password": "password",
  "role": "ADMIN"
}

> {%client.global.set("auth-token", response.body);%}

### Query the demo endPoint
GET http://localhost:8080/contactor/get
Authorization: Bearer {{auth-token}}

### Change the password
PATCH http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "currentPassword": "password",
  "newPassword": "newpassword",
  "confirmationPassword": "newpassword"
}

### Login again and update the token

POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "mohsen@gmail.com",
  "password": "newpassword"
}

> {% client.global.set("new-auth-token", response.body); %}

### Query the demo endPoint after password change
GET http://localhost:8080/contactor/get
Authorization: Bearer {{new-auth-token}}

